### ISSUE TITLE
Support SSR in dynamic routers

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-incubator#18]
See repro repo: https://github.com/levitanong/repro-dr-ssr

```
clojure -m repro.server
```

Stacktrace:

```
Exception in thread "main" java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.lang.Class
	at clojure.core$instance_QMARK___5389.invokeStatic(core.clj:144)
	at clojure.core$instance_QMARK___5389.invoke(core.clj:144)
	at fulcro.client.primitives$reconciler_QMARK_.invokeStatic(primitives.cljc:501)
	at fulcro.client.primitives$reconciler_QMARK_.invoke(primitives.cljc:496)
	at fulcro.incubator.ui_state_machines$get_active_state.invokeStatic(ui_state_machines.cljc:1090)
	at fulcro.incubator.ui_state_machines$get_active_state.invoke(ui_state_machines.cljc:1087)
	at repro.root.RootRouter_klass.render(root.cljc:18)
	at repro.root.RootRouter_klass._render(root.cljc:18)
	at fulcro.client.dom_server$render_component.invokeStatic(dom_server.clj:208)
	at fulcro.client.dom_server$render_component.invoke(dom_server.clj:203)
	at fulcro.client.dom_server$element$fn__14069.invoke(dom_server.clj:229)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core.reducers$reduce.invokeStatic(reducers.clj:46)
	at clojure.core.reducers$reduce.invoke(reducers.clj:38)
	at fulcro.client.dom_server$element.invokeStatic(dom_server.clj:220)
	at fulcro.client.dom_server$element.invoke(dom_server.clj:210)
	at fulcro.client.localized_dom_server$div.invokeStatic(localized_dom_server.clj:45)
	at fulcro.client.localized_dom_server$div.doInvoke(localized_dom_server.clj:45)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at repro.root.Root_klass.render(root.cljc:28)
	at repro.root.Root_klass._render(root.cljc:23)
	at fulcro.client.dom_server$render_component.invokeStatic(dom_server.clj:208)
	at fulcro.client.dom_server$render_component.invoke(dom_server.clj:203)
	at fulcro.client.dom_server$render_to_str_STAR_.invokeStatic(dom_server.clj:387)
	at fulcro.client.dom_server$render_to_str_STAR_.invoke(dom_server.clj:381)
	at fulcro.client.dom_server$render_to_str.invokeStatic(dom_server.clj:398)
	at fulcro.client.dom_server$render_to_str.invoke(dom_server.clj:397)
	at repro.server$index_html.invokeStatic(server.clj:39)
	at repro.server$index_html.invoke(server.clj:35)
	at repro.server$_main.invokeStatic(server.clj:42)
	at repro.server$_main.invoke(server.clj:41)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by awkay** [comment]
Right....not sure what that'll take. I don't have time to test changes, and we probably need some simple state helpers for the routing to set up the correct state/queries.  Glad to talk you through it if you want to attempt a PR, but cannot say when I'd get to it.

**Comment by levitanong** [comment]
Alas, I find myself wanting for time as well. `begin` from state machines is a bigger priority for me, so I'll work on that first. :) I think this particular issue can wait.

**Comment by awkay** [comment]
I've added a basic helper to dynamic routing for generating the correct initial state.  I tested that it generates correct server output, but not that the client will start correctly (or completely) given that state.
